Web1팀 교육 제안서 리뷰 요청합니다!
sullivanproject/2020-h2-step2 pull request #2
Opened 2020-11-12 06:22 UTC by 1914386

**피드백 반영 사항** (자세한 내용은 Web1팀 피드백.md 파일을 참고해주세요!)
1. 서버 운영에 관하여: 서버를 사용하면 추가비용이 발생하기 때문에, 수강자의 자유에 따라 서버를 운영하고 싶은 사람만 서버를 운영할 수 있도록 하겠습니다.
2. 파이썬, 장고의 난이도가 높다는 의견을 반영하여 학교 위키 페이지에 필요한 기능들에 초점을 맞춰서 설명을 할 예정입니다. Python의 경우 Django로 CRUD(Create, Read, Update, Delete) 총 4개의 함수를 이해하고 구현할 줄 아는 것을 목표로 할 것이기 때문에 이 기능을 익히는데 필요한 문법 위주로 교육할 것입니다.
3. 위키 정보의 투명성을 위해 학생증 등 입증 가능한 자료를 통해 인증받은 학생에게만 내용을 추가/수정/삭제할 수 있는 관리자 기능을 부여할 예정입니다.
4. 위키 운영 중 발생할 윤리적/법적 문제를 예방하기 위해 학생들과 함께 위키 규칙을 만드는 시간을 가질 예정입니다. 선생님들이 전반적인 가이드라인을 제시하면 학생들이 자유롭게 아이디어를 내어 규칙을 완성할 수 있도록 할 것입니다.

**멘토님들께 조언을 구하고 싶습니다!**
초기에 교육을 기획할 때는 회원가입 및 로그인 기능을 고려하지 않았는데, 학교 위키라는 특성상 학교에 다니는 학생들에게만 관리자 기능을 부여하는 것이 맞다고 생각하였습니다. 회원가입/로그인 기능을 구현하기 위해서는 어떤 기술이 필요한지 궁금합니다. 그리고 학생들이 해당 기술을 추가적으로 배우는데 어려움은 없을지 멘토님들의 조언을 듣고 싶습니다.

2020-11-12 07:02 UTC, semonec commented
우선적으로 어떤 기술을 사용할지 확실히 정리하는게 중요할거 같아요.
백엔드가 장고를 쓰게 된다면, 데이터베이스는 어떤걸 쓸지, 프론트엔드는 어떤걸 쓸지 먼저 정하는게 가장 중요하다고 봅니다.
여기서 문제가 되는게, 백엔드와 프론트엔드가 같은 언어로 쓰일지, 다른 언어로 쓰일지에 따라서 러닝스텝이 더 늘어날수도, 줄어들 수도 있어요.

위키를 구성하는데 있어서 쓰일 기술을 찾기보다는, 패키지를 설치하고 환경을 설정하고, 
이를 커스터마이징 하는 방향으로 가는건 어떨까 싶기도 합니다. 
위키 구성해주는 패키지들이 꽤 있어서요..
생각보다 할일이 많지 않나 라고 생각이 듭니다.

좀만 컴팩트하게 줄이시고, 이를 통해 어떠한 배움을 가질 수 있는지 한가지 적어두고,
이를 이루기 위한 도움이라는 측면에서 진행해보시는게 좋을것 같아요.

2020-11-12 07:04 UTC, semonec requested changes
조금 더 적어보면, 프론트엔드 사이드의 구현도 생각처럼 쉽지 않으리라 하는 생각도 듭니다.
로그인 기능을 처리하고자 한다면 결국엔 라우터도 적용해야 할거구요.
라우터까지 들어가게 되면 생각보다 큰 프로젝트가 되지 않을까 하는 걱정입니다.

2020-11-12 11:49 UTC, 1914386 commented
> ~~3. 위키 정보의 투명성을 위해 학생증 등 입증 가능한 자료를 통해 인증받은 학생에게만 내용을 추가/수정/삭제할 수 있는 관리자 기능을 부여할 예정입니다.~~

학생들에게 너무 어려운 내용이기 때문에 회원가입 및 로그인 기능은 교육 내용에서 제외하기로 했습니다.

2020-11-13 02:17 UTC, semonec commented
추가적으로 조금더 적어보면

**1. 개발환경**
 - 구름ide 같은 툴을 이용하시면 모두가 같은 개발 환경에서 개발이 가능합니다. 이걸 이용하시면 환경에 따른 차이 문제를 해결할 수 있을거에요.

**2.  backend 개발한 것에 대한 테스트 방법 제시**
 - 아마도 postman 이 되지 않을까 싶은데요. postman 같은 프로그램을 이용한 request - response 가 어떻게 이뤄지는지 직접 실습을 통해 서버와 클라이언트의 통신에 대한 개념을 이해할 수 있게끔 잡아주는게 좋을거 같아요.

**3. 프론트엔드 업무와의 연동 안내**
 - 프론트엔드가 어떻게 준비되어서 실행될 지 잘 모르겠지만, 적어도 백엔드에서 수행한 작업이 매번 프론트엔드에서 볼 수 있게 해준다면 흥미를 유지하는데에도 큰 도움이 되지 않을까 싶습니다. 

**4. 되도록이면 많은 툴을 이용해서 도움받기**
 - 이게 가장 중요한게 아닐까 싶은데요. 상용/프리 툴들을 이것저것 찾아보면서 최대한 학생이 편하게 진행할 수 있게끔 하는게 제일 중요해요.
 - 1차시때 얼마나 환경에 대해 알려주고, 이를 어떻게 활용할지 알려준다면 매우 큰 도움이 되지 않을까 싶어요.
 - 제 경우도, 실무에서 툴없으면 일 하는데 엄청나게 효율성이 떨어지거든요...

2020-11-13 02:21 UTC, semonec commented
추가 comment로 aws free tier도 있고 heroku 같은곳도 deployment 후 일정 트래픽까지는 무료입니다.
충분히 개발 테스트용으로는 가능해요.
개발, 배포 까지 원스텝으로 ide에서 지원되는게 많으니 한번 찾아보시는게 좋을거 같아요.

2020-11-13 02:25 UTC, semonec commented
자바스크립트를 쓰신다면 next.js를 기본 프레임워크로 잡고 next.js 기반의 CRA를 베이스로 해서 만들어보시는것을 추천합니다.
리액트가 어떻게 보면 어려운데, 어떻게 보면 또 쉽거든요.

2020-11-15 11:19 UTC, jypthemiracle requested changes
수고 많으셨습니다. 마크다운에 있는 내용에 대해 상세하게 피드백하였어요.
고민해보시고 추후 교육자료 제작에 반영을 고려해주시면 좋겠네요!

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +   ==> **저희 팀은 실시간 온라인 수업을 진행하여 화면공유, 원격 조종 등을 통해 즉각적인 피드백을 제공할 것입니다. 강의 자료에 설치 시 발생할 오류들과 대처법을 추가할 것입니다. 기타 질문이 있을 경우에는 온라인 QnA 게시판을 적극적으로 활용할 것입니다.**
선생님과 학생의 끊임없는 연결은 정말 중요하죠. 즉문즉답마냥 언제나 연결되어 있다고 느끼면 그만한 심리적 안정감이 또 없을 거에요.
그런데 그냥 당장 안된다고 바로 선생님을 찾기 보다는, 뭔가 학생이 고민해보고 스스로 어려운 점을 정리해서 잘 질문하도록 유도하는 것도 중요하겠지요.
사실 GitHub의 Pull Request를 잘 사용하면 이것이 가능해요. 미션을 여러 단계로 나누고, 단계 하나를 풀다가 잘 모르겠으면 '일단' 내가 한 것에 대한 소스코드를 올리고 일정한 양식에 따라 나의 상황을 정리해서 질문을 올리도록 하면 학생도 공부가 되고, 선생님도 빠르게 답변할 수 있지요. 항상 대기하겠다! 도 좋지만, 어떻게 하면 헬렌 학생들이 좋은 질문을 던지게 할 수 있을까? 를 고민해보고 좋은 질문을 던질 수 있는 환경을 구축해보도록 하세요.

참고할 만한 영상: https://youtu.be/L2p1mdpxD5w

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +    ==> **1주차 때 웹에 대한 전체적인 설명을 하고, 개발환경 설치를 실습으로 진행할 예정업니다. 교육 때 사용할 버전을 미리 정해두어 학생들에게 안내할 것이며, 이미 설치를 완료한 학생의 경우 버전 확인을 하고 필요 시 업데이트 과정을 설명해줄 것입니다.**
아예 구름 IDE 클라우드를 이용하는 방법도 있어요. 특히 온라인 수업을 메인으로 진행하게 된다면 온라인 IDE에서 개발을 하도록 유도한다면 버전관리는 쉬울거에요. 지난 번에 이렇게 진행한 팀이 있지 않았나요? @hiddenest

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +   ==> **일차적으로 사이트를 만들어보는 것에 의의를 두고자 합니다. 따라서 서버 배포까지는 진행하지 않을 예정입니다.**
서버 배포가 사실 어렵지 않아요. [Heroku](https://www.heroku.com/) 라는 서비스를 이용하면 코드 한 줄로 배포가 가능하기 때문에, 아주 어려운 배포를 하지 않더라도 괜찮아요.

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +  ==> **파이썬, 장고의 난이도가 높다는 의견을 반영하여 Javascript로 사용 언어를 변경하였습니다.**
자바스크립트가 아무래도 처음에 접근하기에 좋은 언어라고 생각해요.
당장 구글 크롬 콘솔창을 켜서 이것저것 만지면 아주 사람들이 신기해하죠. 웹사이트가 막 바뀌니까요 ㅎㅎ

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +  **사전에 먼저 위키를 만들어보며 참고한 사이트, 동영상 등의 학습 자료를 학생들에게 공유하여 수업 전에 미리 훑어보고 오는 방식을 고려하고 있습니다.**
단순히 학습 자료를 공유하면 잘 안 읽고 올 수도 있어요. (제가 그래서 ㅎㅎ)
대신, 헬렌 학생들에게 수업에 오기 전에 간단한 사전과제를 던져주고 이에 대한 리뷰를 하면서 현장 강의를 시작하는 방법도 고민해볼 수 있겠습니다.

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +   ==> **위키의 내용을 입력하고 관리하는 것은 학생 본인이며, 선생님들은 위키의 내용이 위키의 규칙에 위배되지 않는지 확인하는 역할을 맡을 것입니다. 따라서 학습자를 관리할 때 위키의 내용이 헷갈릴 우려는 없을 것입니다.**
로그인이나 회원가입, 학생 인증 등은 수업이 끝나고 프로젝트를 더 발전시켜 프로토타입 형태를 진짜 서비스까지 끌어올리고 싶을 때 선생님들이 도와줄 수 있을 거라고 이야기하면 좋을 것 같아요. 그리고 굳이 선생님이 체크하기 보다는.. 학생들이 자치적으로 해결할 수도 있겠지요. 하여튼 이 부분은 헬렌들이 주도적으로 고민해보면서 프로젝트를 가꿔보도록 유도해주세요.

2020-11-15 11:19 UTC, jypthemiracle commented on WebTeam1/Web1팀 피드백.md
> +   ==> **학생들과 선생님이 만든 자치 규정에 의거하여 적절한 조치를 취하도록 할 것입니다.**
이 부분도 뭔가 정답을 내려주기 보다는,
헬렌 학생들이 자신이 처한 상황에서 주도적으로 답을 내릴 수 있도록 화두를 던져주면 좋을 것 같아요. 여러분이 고민할 문제가 아니라, 프로젝트를 진행하는 학생들이 고민할 문제겠네요 ㅎㅎ

2020-11-15 14:16 UTC, 1914386 commented on WebTeam1/Web1팀 피드백.md
> +   ==> **일차적으로 사이트를 만들어보는 것에 의의를 두고자 합니다. 따라서 서버 배포까지는 진행하지 않을 예정입니다.**
그렇다면 이 부분에 관해서는 다시 한번 논의해서 결정하겠습니다!

2020-11-16 02:14 UTC, semonec commented on WebTeam1/Web1팀 피드백.md
> +   ==> **일차적으로 사이트를 만들어보는 것에 의의를 두고자 합니다. 따라서 서버 배포까지는 진행하지 않을 예정입니다.**
구름 ide를 쓰면 heroku 배포까지도 원클릭으로 됩니다. 어렵지 않아요...

2020-11-16 02:15 UTC, semonec approved these changes
잔여 문제들은 다음번에 구체화하는거로 하면 좋을거 같습니다.

2023-01-06 07:07 UTC, closed without merging