Web2팀 교육 제안서 리뷰 요청합니다
sullivanproject/2020-h2-step2 pull request #3
Opened 2020-11-13 16:41 UTC by YouSuhyung

<바뀐점>
1. 모집인원을 6명으로 하여 선생님 한명 당 2명을 커버하고 2명이 서로 도움을 줄 수 있게 팀을 구성 하였습니다.
2. 학생들과의 소통을 위해 1~4 차시는 녹화수업으로 진행하고 5~8차시는 대면 강의로 구성하였습니다.
3. 매 차시 끝난 후 학습한 내용을 자신의 지도에 적용할 수 있는 시간을  부여하고 8차시에는 자신의 지도를 완성, 공유하는 시간을 부여하였습니다.
4. 질문할 수 있는 소통 창구를 마련하였습니다.

2020-11-14 01:24 UTC, semonec commented
Web2 팀은 특징이 엄청 잘 드러나네요.
어떻게 운영 하는지에 따라 결과가 아주 다르게 나타날 것 같아요.

**Good**
* 비대면의 어려움이 무엇인지 파악하고 있는것 같아요. 수업을 진행함에 있어서 어려움이 가장 적어보입니다.
* 녹화 + 대면으로 부족할 수 있는 부분을 채우고, 준비가 부족한 부분을 사전녹화에서 파악해서 실제 강의 시 적용할 수 있어보여요.
* 각 차시별 목표가 뚜렷하기에 세부 사항만 정리하면 큰 문제가 없을거 같아요.

**To be Improved**
* 대상이 이미 프로그래밍이 무엇인지 아는, 어떻게 하는 지 아는 사람인건가요? 다른 팀에도 이야기 하지만, 초반 러닝커브에 대해서 가볍게 생각한게 아닐까 하는 걱정입니다. 언어 자체를 이해하지 못한다면 8주차의 커리큘럼을 따라가기 힘들지 않을까 하는 생각입니다.
* 다른 팀에도 이야기 했지만, 단순한 기술 교육이 아니라 기술을 바탕으로 한 무언가 다른것을 얻음을 목적으로 가지면 어떨까 하는 생각입니다.
사회문제의 해결같은 뭔가 이상적인 목적은 아니더라도, 이를 통해서 다른 무언가를 획득할 수 있을지를 목표로 해보시는게 어떨까 싶습니다.
* 5차시의 지도 내용 구상이 좀더 앞으로 와서 수행함에 있어서 목적성을 확실히 가져주었으면 하는 바램입니다.
* 아마 JS를 쓰시게 된다면, API 처리가 async나 Promise가 들어가게 될텐데, 이론이 부족한 학생들이 가장 힘들어하는게 이 async 처리에 대한 사항입니다. 이걸 좀더 신경써주셔야 원하는 목표가 제대로 나오지 않을까 싶습니다.
* fe framework가 어떤게 들어갈 지 정의되지 않은것 같은데, 이것에 대한 정의도 우선적으로 선행되어야 할 것 같아요. fe framework 에 따라서 방향성이 극명이 갈리게 되니깐요.

2020-11-14 01:25 UTC, semonec requested changes
위 코멘트를 참조해주시면 감사하겠습니다.
준비를 많이 하신 느낌이 들어서 좋네요.

2020-11-14 12:18 UTC, Leemainsw commented
와 정말 기대되는 교육이네요! 학생들의 이해를 돕기 위해 미리 예시를 만들어보여드리는 것도 좋은 방법일 것 같아요! 😀😀

2020-11-15 10:59 UTC, jypthemiracle commented
세문님이 위에 좋은 커멘트를 남겨주셨네요 ^~^
저도 추가로 붙이자면 다음으로 요약해볼 수 있겠네요.
1. 지도를 통해 '어떤' 웹사이트를 만들지 먼저 고민해보도록 해주세요.
- 이것은 1차시에 들어가면 좋습니다. 학생들이 스스로 내가 뭘 만들지 상상의 나래를 펼치면서 자신만의 목표를 잡는 기회가 되기도 하고, 너무 기술적으로 구현이 어려운 사항을 사전에 잘라내는 역할을 하기도 합니다.
2. 사전과제 또는 비대면 과제의 경우에는 같이 '회고' 해보는 시간을 갖도록 해주세요.
- 대면강의는 설리번 선생님과 헬렌 학생이 함께 문제를 해결해가는 기회가 있지만, 사전과제나 비대면 과제는 상호 피드백을 할 수 있는 기회가 부족하지요. 이를 보충할 수 있는 방법을 생각해야 합니다. 예를 들어 오늘의 미션을 내준다면, 아침부터 9시까지 제출할 수 있도록 하고 밤 10시에 같이 온라인으로 접속해서 미션에 대한 리뷰를 하는 방식을 생각해볼 수 있겠어요.
3. 기타로 프론트엔드 프레임워크를 확정지어야 하는데, 아무래도 Vue.js 사용하는 것이 낫지 않을까 싶습니다. 난이도 면에서 용이한데요. 그렇지요? 제가 그런데 뷰를 사용해본 적이 없어서 ㅎㅎㅎ @semonec

2020-11-15 12:01 UTC, juneverbena commented
프론트엔드 프레임워크로 일단 Node.js로 정하고 express를 통해 로컬host에서 돌아갈 수 있도록 하기로 했는데 제가 Node.js는 써봤지만 Vue.js는 한번도 써보지 않아서.... 그렇다면 Node.js 환경이 좋겠지요?  @jypthemiracle

2020-11-15 12:07 UTC, jypthemiracle commented
으음.. Node.js는 프론트엔드 프레임워크가 아닙니다. Node.js는 자바스크립트 런타임 환경으로 알고 있어요. ㅎㅎ
말씀하신 express 프레임워크는 백엔드 프레임워크일 겁니다. ㅎㅎ 아마 express를 사용해보셨다면 알겠지만 웹 사이트를 동적 html로만 표현하실 거에요.

2020-11-15 12:22 UTC, juneverbena commented
@jypthemiracle 아 제가 잘못생각했네요. 근데 저희 팀원들도 그렇고 저도 vue.js 사용을 해보질 않았는데 괜찮을까요? 원래 html 템플릿으로만 작동하려 했거든요

2020-11-15 12:26 UTC, jypthemiracle commented
만약 프론트엔드 프레임워크를 사용하고 싶으시다면 Vue.js가 제일 쉽다고 들었어요. 세문님 @semonec 과 상의하셔서 결정해보세요!

2020-11-15 12:27 UTC, juneverbena commented
@semonec vue.js를 한번도 사용안해본 사람 입장에서 vue.js 사용까지 한꺼번에 가능한가요..?

2020-11-15 12:28 UTC, juneverbena commented
@semonec HTML 템플릿 말고 FE framework를 꼭 사용해야 하는 이유는 무엇인가요..? 사용해본적이 없어서 잘 모르기 때문에 질문드립니다.

2020-11-16 02:19 UTC, semonec commented
@juneverbena 
슬랙에 적었긴 합니다만 좀더 정리해보자면,
충분히 html template과 약간의 js만으로도 가능합니다.
그렇지만, 외부 라이브러리 (특히 http request 처리) 와의 연동시에 코드가 좀 더 길어지고 복잡해지는 문제가 있을 수 있어요.
코드가 모듈화 되지 않아서 다소 복잡해집니다. 이해가 어려워져요.
문제가 생겨도 잡기가 쉽지 않습니다.
어디서부터 문제인지 찾기가 힘들어져요.

하지만 얼마든지 가능은 합니다.

2020-11-16 09:01 UTC, juneverbena commented
@semonec 답변해주셔서 감사합니다

2022-06-17 13:11 UTC, closed without merging